package exercise1;

/**
 * @file Game.java
 * @author Kevin Ma | #: 300867968
 * @date December 3, 2016
 * @version 0.2.0 added models corresponding to the tables in the database
 * @description This class is a model for the Game table in the database.
 * 
 */

public class Game {
	// Instance variables
	private final int gameId;
	private String gameTitle;

	// public properties
	// NOTE: game_id is auto-generated by sequence in database, so we don't
	// need setter method for it
	public int getGameId() {
		return gameId;
	}

	public String getGameTitle() {
		return gameTitle;
	}

	public void setGameTitle(String gameTitle) {
		this.gameTitle = gameTitle;
	}

	// constructor
	public Game(int id) {
		this.gameId = id;
	}
}
