package models;

/**
 * @file Game.java
 * @author Kevin Ma | #: 300867968
 * @date December 10, 2016
 * @version 0.6.2 - completed layout for PlayerAndGameView
 * @description This class is a model for the Game table in the database.
 * 
 */

public class Game {
	// INSTANCE VARIABLES
	// =============================================================================================
	private final int gameId;
	private String gameTitle;

	// PUBLIC PROPERTIES
	// =============================================================================================
	// NOTE: game_id is auto-generated by sequence in database, so we don't
	// need setter method for it
	public int getGameId() {
		return gameId;
	}

	public String getGameTitle() {
		return gameTitle;
	}

	public void setGameTitle(String gameTitle) {
		this.gameTitle = gameTitle;
	}

	// CONSTRUCTOR
	// =============================================================================================
	public Game(int id) {
		this.gameId = id;
	}

	public String toString() {
		return String.format("%s", this.gameTitle);
	}
}
