package models;

/**
 * @file Player.java
 * @author Kevin Ma | #: 300867968
 * @date December 8, 2016
 * @version 0.5.1 updated Models comments
 * @description This class is a model for the Player table in the database.
 * 
 */

public class PlayerModel {
	// INSTANCE VARIABLES
	// =============================================================================================
	private final int playerId;
	private String firstName;
	private String lastName;
	private String address;
	private String postalCode;
	private String province;
	private String phoneNumber;

	// PUBLIC PROPERTIES
	// =============================================================================================
	// NOTE: player_id is auto-generated by sequence in database, so we don't
	// need setter method for it
	public int getPlayerId() {
		return playerId;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostalCode() {
		return postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	// CONSTRUCTOR
	// =============================================================================================
	public PlayerModel(int id) {
		this.playerId = id;
	}
}
